In [45]:
from scipy import misc
import matplotlib.pyplot as plt
import numpy as np
import cv2
import os
from os import listdir
from os.path import isfile, join
import csv
import random
#import imageio
#from skimage import io

def create_csv():
    processAll()
    #process1image('test/test1.jpg')

#traverses all images in directory
def processAll():
    for root, dirs, files in os.walk("/dataset"):
        for file in files:
            if file.endswith(".jpg"):
                processimages( (os.path.join(root, file)), file)
                #print(os.path.join(root, file))
    
#creates resized image and writes to csv    
def processimages(location,filename):
    nrows = 50
    ncols = 50

    img = misc.imread (location)
    type (img)
    #[height, width, dim] = img.shape
    #print(dim)
    res_img = cv2.resize(img,(ncols,nrows))

    newimg = np.zeros((nrows, ncols), dtype=int)

    imgYCC = cv2.cvtColor(res_img, cv2.COLOR_BGR2YCR_CB)
    cb = imgYCC[:,:,1]
    cr = imgYCC[:,:,2] 
    #print("cb is :", cb)
    [height, width, dim] = res_img.shape
    #print(height)

    cen_col = imgYCC[int(height/2),int(width/2),:] 
    #print("imycc vals: ",imgYCC)
    cb_col = cen_col[1]
    #print("cb_col is: ",cb_col)
    cr_col = cen_col[2]
    #The range of vals
    cb_diff = 17;
    cr_diff = 10;
    # find skin-coloured pixels in range
    a = np.where((cb>=(cb_col-cb_diff)) & (cb<=(cb_col+cb_diff)) &(cr>=(cr_col-cr_diff)) & (cr<=(cr_col+cr_diff)) )
    #print(a[0].size)
    # Mark detected pixels
    for i in range(0,(a[0].size)-1):
        newimg[ a[0][i], a[1][i] ] = 255
    cv2.imwrite("processed/%s" % filename, newimg)
    print(filename)
    print("hello")
    
    if(filename[0]=="s"):#stop
        newimg = np.append(newimg, [1,0,0,0])
    elif(filename[0]=="p"):#peace
        newimg = np.append(newimg, [0,1,0,0])
    elif(filename[0]=="t"):#trek
        newimg = np.append(newimg, [0,0,1,0])
    else:#L
        newimg = np.append(newimg, [0,0,0,1])    
        
    a = newimg.flatten()
    
    number = random.randint(1,10)
    if(number>2):
        outfile = "train_data.csv"
    else:
        outfile = "test_data.csv"
    
    if (filename == "stop660.jpg"):#if its the first file - name
        open("train_data.csv", 'w+').close()
        open("test_data.csv", 'w+').close()
        
    with open(outfile, 'a') as my_csv:
        csvWriter = csv.writer(my_csv,delimiter=',')
        csvWriter.writerow(a)


def process1image(location):
    nrows = 50
    ncols = 50

    img = misc.imread (location)
    type (img)
    res_img = cv2.resize(img,(ncols,nrows))
    newimg = np.zeros((nrows, ncols), dtype=int)

    imgYCC = cv2.cvtColor(res_img, cv2.COLOR_BGR2YCR_CB)
    cb = imgYCC[:,:,1]
    cr = imgYCC[:,:,2] 
    #print("cb is :", cb)
    [height, width, dim] = res_img.shape
    #print(height)

    cen_col = imgYCC[int(height/2),int(width/2),:] 
    cb_col = cen_col[1]
    cr_col = cen_col[2]
    #The range of vals
    cb_diff = 17;
    cr_diff = 10;
    # find skin-coloured pixels in range
    a = np.where((cb>=(cb_col-cb_diff)) & (cb<=(cb_col+cb_diff)) &(cr>=(cr_col-cr_diff)) & (cr<=(cr_col+cr_diff)) )

    # Mark detected pixels
    for i in range(0,(a[0].size)-1):
        newimg[ a[0][i], a[1][i] ] = 1 #255 instead of 1 for binary

    a = newimg.flatten()
    return(a)
#if __name__ == '__main__':
#np.random.seed(42)
#create_csv()
    #x_train, y_train, x_test, y_test = load_dataset()


In [46]:
if __name__ == '__main__':
    np.random.seed(42)
    create_csv()
    print("asdfg")

asdfg


In [47]:
def load_dataset(train_dataset='train_data.csv', test_dataset='test_data.csv'):
    """
    Loads and returns train and test datasets.
    """
    data_train = np.genfromtxt(fname=train_dataset, delimiter=',')
    y_train = data_train[:,2500:].astype(np.int)
    x_train = (data_train[:,:2500]/ 255).astype(np.int)
    data_test = np.genfromtxt(fname=test_dataset, delimiter=',')
    y_test = data_test[:,2500:].astype(np.int)
    x_test = (data_test[:,:2500]/ 255).astype(np.int)
    return (x_train, y_train, x_test, y_test)
x_train, y_train, x_test, y_test = load_dataset()

In [48]:
print(x_train.shape[0])# # of rows
print(x_train.shape[1])# # of cols
print(y_train.shape[0])#
print(y_train.shape[1])#
print(y_train)

186
2500
186
4
[[1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 

In [49]:
def sigmoid(x):  
    return 1/(1+np.exp(-x))

def sigmoid_der(x):  
    return sigmoid(x) *(1-sigmoid (x))

def softmax(A):  
    expA = np.exp(A)
    return expA / expA.sum(axis=1, keepdims=True)

class ANeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.y          = y
        #weight matrices
        self.mat_w1   = np.random.rand(self.input.shape[1],50) 
        self.mat_w2   = np.random.rand(50,4)                 
        #output for classification
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.inp_layer = sigmoid(np.dot(self.input, self.mat_w1))
        self.output = sigmoid(np.dot(self.inp_layer, self.mat_w2))

    def backprop(self):
        d_weights2 = np.dot(self.inp_layer.T, (2*(self.y - self.output) * sigmoid_der(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_der(self.output), self.mat_w2.T) * sigmoid_der(self.inp_layer)))
        self.mat_w1 += d_weights1
        self.mat_w2 += d_weights2
    def train(self):
        nn.feedforward()
        nn.backprop()
    def pred(self, inp):
        self.inp_layer = sigmoid(np.dot(inp, self.mat_w1))
        self.output = sigmoid(np.dot(self.inp_layer, self.mat_w2))

        
if __name__ == "__main__":
    nn = ANeuralNetwork(x_train,y_train)

    for i in range(2500):
        nn.train()
        
print(nn.output)

[[9.89434892e-001 4.28332911e-003 1.44268768e-005 2.88205349e-002]
 [9.89434892e-001 4.28332911e-003 1.44268768e-005 2.88205349e-002]
 [9.89434892e-001 4.28332911e-003 1.44268768e-005 2.88205349e-002]
 [9.89434892e-001 4.28332911e-003 1.44268768e-005 2.88205349e-002]
 [9.89434892e-001 4.28332911e-003 1.44268768e-005 2.88205349e-002]
 [9.89434892e-001 4.28332911e-003 1.44268768e-005 2.88205349e-002]
 [9.89434892e-001 4.28332911e-003 1.44268768e-005 2.88205349e-002]
 [9.89434892e-001 4.28332911e-003 1.44268768e-005 2.88205349e-002]
 [9.89434892e-001 4.28332911e-003 1.44268768e-005 2.88205349e-002]
 [9.89434892e-001 4.28332911e-003 1.44268768e-005 2.88205349e-002]
 [9.89434892e-001 4.28332911e-003 1.44268768e-005 2.88205349e-002]
 [9.89434892e-001 4.28332911e-003 1.44268768e-005 2.88205349e-002]
 [9.89434892e-001 4.28332911e-003 1.44268768e-005 2.88205349e-002]
 [9.89434892e-001 4.28332911e-003 1.44268768e-005 2.88205349e-002]
 [9.89434892e-001 4.28332911e-003 1.44268768e-005 2.88205349e-

In [50]:
#zz = np.amax(nn.output, 1)
predictions = np.zeros_like(nn.output).astype(int)
predictions[np.arange(len(nn.output)), nn.output.argmax(1)] = 1
#print(predictions)
#for i in range(zz.size):
#    print(zz[i])

In [51]:
out_rows = y_train.shape[0]
count = 0
for i in range (out_rows):#y_train[outrows-1]
    if np.all(y_train[i]==predictions[i]):
        count += 1
train_acc = (count/out_rows)*100
print("Training accuracy is:", train_acc, "%")

Training accuracy is: 99.46236559139786 %


In [52]:
#y = np.array([[0],[1],[1],[0]])
#ann2 = ANeuralNetwork(x_test,y_test)

for i in range(1):
    nn.pred(x_test)
pred_test = np.zeros_like(nn.output).astype(int)
pred_test[np.arange(len(nn.output)), nn.output.argmax(1)] = 1
print(pred_test)
    #nn.backprop()

[[1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 0 1]
 [0 1 0 0]]


In [53]:
test_out_rows = y_test.shape[0]
count1 = 0
for i in range (test_out_rows):#y_train[outrows-1]
    if np.all(y_test[i]==pred_test[i]):
        count1 += 1
test_train_acc = (count1/test_out_rows)*100
print("Test set accuracy is:", test_train_acc, "%")

Test set accuracy is: 70.0 %


In [57]:
def getmypred(file):
    myimg = process1image(file)
    #print(myimg)
    for i in range(1):
        nn.pred(myimg)
    a = np.zeros((1,4)).astype(int)
    a[0][nn.output.argmax(0)]=1
    #print(nn.output)
    if(np.sum(a[0])<0.1):
        print("none")
    elif(np.all(a[0]==[1, 0, 0, 0])):
        print("stop")
    elif(np.all(a[0]==[0, 1, 0, 0])):
        print("peace")
    elif(np.all(a[0]==[0, 0, 1, 0])):
        print("trek")
    else:
        print("L")



In [59]:
import time

cap = cv2.VideoCapture(0)
count = 0
while(True):
    s_time= time.time()
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Our operations on the frame come here
    #gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Display the resulting frame
    if(count%15==0):
        cv2.imwrite("frame%d.jpg" % count, frame)
        getmypred("frame%d.jpg" % count)
        os.remove("frame%d.jpg" % count)
    cv2.imshow('frame',frame)
    #cv2.imwrite("frame%d.jpg" % count, frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    count += 1
    #time.sleep(0.1 + (time.time() - s_time))

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()

/home/zab/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:93: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.


stop
stop
stop
stop
stop
stop
stop
L
L
L
trek
trek
trek
L
L
L
trek
trek
trek
trek
stop
stop
stop
stop
trek
stop
stop
stop
stop
stop
stop
stop
stop
stop
stop
stop
trek
trek
trek
stop
trek
stop
stop
stop
stop
stop
trek
trek
trek
trek
trek
trek
trek
trek
peace
peace
peace
peace
trek
peace
peace
trek
trek
stop
stop
peace
peace
peace
peace
trek
trek
stop
stop
stop
peace
peace
peace
peace
peace
peace
stop
stop
stop
stop
L
L
L
L
L
L
L
L
L
trek
L
trek
stop
stop
stop
stop
stop
stop
stop
trek
trek
trek


In [56]:
cap.release()
cv2.destroyAllWindows()